### ISSUE TITLE
PayPalExpressPrepareConverter does not decrypt response data

### ISSUE THREAD

**Issue by DonFlurry** [spryker-eco/computop-api#10]
Reproduce:
Problem occurs when pressing the PayPal Express button in the shopping cart.

Technical description:
AbstractPayPalExpressRequest sends an encrypted data string to Computop. The response that we then get back is also encrypted.
Unfortunately, the PayPalExpressPrepareConverter does not decrypt the response data, which means that it is lost when it is mapped to the transfer object.

Furthermore, the PayPalExpressPrepareConverter does not extend the AbstractConverter.

References:
\ SprykerEco \ Zed \ ComputopApi \ Business \ Converter \ AbstractConverter
\ SprykerEco \ Zed \ ComputopApi \ Business \ Converter \ ExpressCheckout \ PayPalExpressPrepareConverter
\ SprykerEco \ Zed \ ComputopApi \ Business \ Request \ ExpressCheckout \ AbstractPayPalExpressRequest

**Comment by DonFlurry** [comment]
UPDATE / New Info:
We deducted that we actually used the wrong endpoint, but now we are using the correct one: https://www.computop-paygate.com/paypal.aspx

The current problem is that in the converter here:
\ SprykerEco \ Zed \ ComputopApi \ Business \ Converter \ ExpressCheckout \ PayPalExpressPrepareConverter

We receive the HTML of the PayPal login as a response to our request. The HTML can obviously not be mapped to the transfer object (ComputopApiPayPalExpressPrepareResponseTransfer). We assume that we should not receive HTML at all. Sadly we were unable to find any examples for this scenario. Can you please advise?

**Comment by zamo-po** [comment]
Hi @DonFlurry, you should contact Computop directly to adjust computop in your current project (`PaypalExpress configuration`). Only then computop API will start responding with correct output (Non HTML, PayPal Express will not work with default PayPal connected to Computop).

Also to prepare request next URL should be used: 
`https://www.computop-paygate.com/ExternalServices/paypalorders.aspx`

**Comment by zamo-po** [comment]
> UPDATE / New Info: We deducted that we actually used the wrong endpoint, but now we are using the correct one: https://www.computop-paygate.com/paypal.aspx
> 
> The current problem is that in the converter here: \ SprykerEco \ Zed \ ComputopApi \ Business \ Converter \ ExpressCheckout \ PayPalExpressPrepareConverter
> 
> We receive the HTML of the PayPal login as a response to our request. The HTML can obviously not be mapped to the transfer object (ComputopApiPayPalExpressPrepareResponseTransfer). We assume that we should not receive HTML at all. Sadly we were unable to find any examples for this scenario. Can you please advise?

Hi @DonFlurry, you should contact Computop directly to adjust computop in your current project (PaypalExpress configuration). Only then computop API will start responding with correct output (Non HTML, PayPal Express will not work with default PayPal connected to Computop).

Also to prepare request next URL should be used:
https://www.computop-paygate.com/ExternalServices/paypalorders.aspx
